name: EzyFS Service Registry Image
on:
  push:
    branches: [master]
    paths: [k8s/consul]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: docker login
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Build the Docker image
        run:
          docker build -t mellywins/ezyfs-consul:latest -f
          k8s/consul/images/consul.Dockerfile .
      - name: Docker push
        run: docker push mellywins/ezyfs-consul:latest
